# Generated by Django 4.1.1 on 2022-10-31 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_area_categoria_subcategoria_alter_task_datecompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.categoria'),
            preserve_default=False,
        ),
    ]
