# Generated by Django 4.1.1 on 2022-11-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
