# Generated by Django 4.1.1 on 2022-11-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_area_delete_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.subcategoria'),
            preserve_default=False,
        ),
    ]
