# Generated by Django 4.1.1 on 2022-11-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_subcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='complejidad',
        ),
    ]
