# Generated by Django 4.1.1 on 2022-11-21 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_complejidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
